export const supportedLanguages = [
    { code: 'en', label: 'English' },
    { code: 'tr', label: 'Türkçe' },
    { code: 'es', label: 'Español' },
    { code: 'fr', label: 'Français' },
    { code: 'de', label: 'Deutsch' },
    { code: 'ar', label: 'العربية' },
    { code: 'pt', label: 'Português' },
    { code: 'ru', label: 'Русский' },
    { code: 'hi', label: 'हिन्दी' },
    { code: 'zh', label: '中文' },
    { code: 'ja', label: '日本語' },
    { code: 'it', label: 'Italiano' },
    { code: 'nl', label: 'Nederlands' },
    { code: 'ko', label: '한국어' },
    { code: 'sv', label: 'Svenska' },
    { code: 'no', label: 'Norsk' },
    { code: 'da', label: 'Dansk' },
    { code: 'fi', label: 'Suomi' },
    { code: 'pl', label: 'Polski' },
    { code: 'cs', label: 'Čeština' },
    { code: 'el', label: 'Ελληνικά' },
    { code: 'he', label: 'עברית' },
    { code: 'hu', label: 'Magyar' },
    { code: 'ro', label: 'Română' },
    { code: 'sk', label: 'Slovenčina' },
    { code: 'uk', label: 'Українська' },
    { code: 'vi', label: 'Tiếng Việt' },
    { code: 'id', label: 'Bahasa Indonesia' },
    { code: 'ms', label: 'Bahasa Melayu' },
    { code: 'th', label: 'ไทย' },
    { code: 'bn', label: 'বাংলা' },
    { code: 'ta', label: 'தமிழ்' },
    { code: 'te', label: 'తెలుగు' },
    { code: 'mr', label: 'मराठी' },
    { code: 'fa', label: 'فارسی' },
    { code: 'ur', label: 'اردو' },
    { code: 'bg', label: 'Български' },
    { code: 'hr', label: 'Hrvatski' },
    { code: 'sr', label: 'Српски' },
    { code: 'sl', label: 'Slovenščina' },
    { code: 'lt', label: 'Lietuvių' },
    { code: 'lv', label: 'Latviešu' },
    { code: 'et', label: 'Eesti' },
    { code: 'sw', label: 'Kiswahili' },
    { code: 'af', label: 'Afrikaans' },
    { code: 'is', label: 'Íslenska' },
    { code: 'ga', label: 'Gaeilge' },
    { code: 'mt', label: 'Malti' },
    { code: 'am', label: 'አማርኛ' },
    { code: 'hy', label: 'Հայերեն' },
];
